(()=>{
const state={lessons:[],filtered:[],selected:null,intent:null,ready:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
function labelClass(label){return `evidence-${String(label||'').toLowerCase().replace(/_/g,'-')}`}
function detectIntent(q=''){const text=q.toLowerCase();const diagnosis=/\b(miss(?:ing|ed)?|behind|in front|under(?:neath)?|below|above|over|late|early|stop(?:ping|ped)?|lost|losing|rushing|rush|wrong|disappear(?:s|ed)?|occlud(?:e|ed|ing))\b/.test(text);return diagnosis?'diagnose':'learn'}
function terms(q=''){return q.toLowerCase().replace(/[^a-z0-9\s-]/g,' ').split(/\s+/).filter(Boolean).filter(x=>!['on','a','an','the','i','keep','am','my','to','of','at'].includes(x))}
async function loadCertifiedLessons(){const urls=['data/playbook-representative-v1.json?v=20260903-2359','data/playbook-expansion-stage8-v1.json?v=20260904-0425'];const results=await Promise.all(urls.map(async url=>{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.json()}));const lessons=results.flatMap(d=>Array.isArray(d.lessons)?d.lessons:[]);const ids=new Set();for(const l of lessons){if(ids.has(l.id))throw new Error(`Duplicate Playbook lesson id: ${l.id}`);ids.add(l.id)}return lessons}
function setup(){if(state.ready)return;const root=$('#playbookRoot');if(!root)return;state.ready=true;root.setAttribute('aria-busy','true');const list=$('#playbookList');if(list)list.innerHTML='<div class="playbook-empty">Loading certified Playbook lessons…</div>';loadCertifiedLessons().then(lessons=>{state.lessons=lessons;state.filtered=[...state.lessons];root.removeAttribute('aria-busy');renderList();bindSearch()}).catch(err=>{root.removeAttribute('aria-busy');state.ready=false;const count=$('#playbookCount');if(count)count.textContent='Playbook could not load';const target=$('#playbookList');if(target){target.innerHTML=`<div class="playbook-error" role="alert"><strong>Playbook unavailable</strong><span>${esc(err.message)}</span><button class="secondary-button" id="playbookRetry">Try again</button></div>`;$('#playbookRetry')?.addEventListener('click',setup)}})}
function bindSearch(){const input=$('#playbookSearch');if(!input||input.dataset.bound)return;input.dataset.bound='1';input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();state.intent=q?detectIntent(q):null;if(!q){state.filtered=[...state.lessons]}else{const ts=terms(q);state.filtered=state.lessons.map(l=>({l,score:scoreLesson(l,ts,q)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.l)}renderList(q)})}
function haystack(l){return [l.name,...(l.aliases||[]),l.understand,...(l.coaching||[]).map(x=>x.text),...(l.diagnose||[]).flatMap(d=>[d.symptom,...(d.candidate_mechanisms||[]),d.question,d.interpretation,d.fix])].join(' ').toLowerCase()}
function scoreLesson(l,ts,q){const h=haystack(l);let score=0;if(h.includes(q))score+=20;for(const t of ts){if(h.includes(t))score+=3}const aliases=(l.aliases||[]).map(a=>a.toLowerCase());if(aliases.some(a=>q.includes(a)||a.includes(q)))score+=10;if(state.intent==='diagnose'&&(l.diagnose||[]).some(d=>ts.some(t=>haystack({name:'',aliases:[],understand:'',coaching:[],diagnose:[d]}).includes(t))))score+=5;return score}
function renderList(q=''){const list=$('#playbookList');if(!list)return;const count=$('#playbookCount');if(count)count.textContent=q?`${state.filtered.length} ${state.intent==='diagnose'?'diagnostic':'lesson'} matches`:`${state.filtered.length} certified lessons`;const intent=$('#playbookIntent');if(intent){intent.hidden=!q;intent.classList.toggle('diagnose',state.intent==='diagnose');intent.innerHTML=q?(state.intent==='diagnose'?'<strong>Diagnose mode</strong><span>These lessons are ranked against the miss you described. Open one to check likely causes before applying a fix.</span>':'<strong>Learn mode</strong><span>Open the closest presentation to understand the target and available coaching approaches.</span>'):''}if(!state.filtered.length){list.innerHTML='<div class="playbook-empty"><strong>No certified match yet.</strong><span>Try a simpler presentation phrase such as “crosser”, “teal”, “rabbit” or “looper”. ShotSight will not invent advice for an unsupported target.</span></div>';return}list.innerHTML=state.filtered.map(l=>`<button class="playbook-card" data-playbook-id="${esc(l.id)}" data-focus="${state.intent==='diagnose'?'diagnose':'learn'}"><span class="playbook-family">${esc(prettySelector(l.selector))}</span><strong>${esc(l.name)}</strong><small>${esc(l.understand)}</small><span class="playbook-open">${state.intent==='diagnose'?'Diagnose':'Open'} →</span></button>`).join('');list.querySelectorAll('[data-playbook-id]').forEach(b=>b.addEventListener('click',()=>openLesson(b.dataset.playbookId,b.dataset.focus)))}
function prettySelector(s={}){return [s.flight_family,s.phase,s.direction,s.sequence_context].filter(x=>x&&x!=='unknown').map(x=>x.replace(/_/g,' ')).join(' · ')||'presentation lesson'}
function openLesson(id,focus='learn'){state.selected=state.lessons.find(l=>l.id===id);if(!state.selected)return;renderLesson(state.selected,focus);const sheet=$('#playbookSheet');sheet.classList.add('active');sheet.setAttribute('aria-hidden','false');document.body.classList.add('sheet-open');setTimeout(()=>{if(focus==='diagnose')$('#playbookLessonBody .pb-diagnose')?.scrollIntoView({block:'start'})},80)}
function closeLesson(){const sheet=$('#playbookSheet');sheet?.classList.remove('active');sheet?.setAttribute('aria-hidden','true');document.body.classList.remove('sheet-open')}
function diagnosisHtml(diag){return diag?`<section class="pb-section pb-diagnose"><span class="pb-kicker">DIAGNOSE THIS MISS</span>${diag.label?`<span class="evidence-pill ${labelClass(diag.label)}">${esc(diag.label)}</span>`:''}<h3>${esc(diag.symptom)}</h3><p><strong>Possible causes:</strong> ${esc((diag.candidate_mechanisms||[]).join(' · '))}</p><div class="pb-question"><span>CHECK</span><strong>${esc(diag.question)}</strong><p>${esc(diag.interpretation)}</p></div><p><strong>Try:</strong> ${esc(diag.fix)}</p><p><strong>Retest:</strong> ${esc(diag.retest)}</p></section>`:''}
const visualProfiles={
 flat_long_crosser:{path:'M 8 50 L 92 50',labels:[['PICKUP',30,50],['BREAK ZONE',74,50]],note:'Target travels predominantly across the view.'},
 quartering_away:{path:'M 8 70 L 92 30',labels:[['PICKUP',28,60],['AWAY',58,46],['BREAK ZONE',76,38]],note:'Oblique screen path represents across-and-away geometry; it is not a depth simulation.'},
 low_fast_incomer_cutoff:{path:'M 10 28 C 38 32 58 40 70 50 C 80 60 85 72 92 82',labels:[['EARLY FLIGHT',26,31],['TRANSITION',69,50],['FINAL LINE',82,67],['BREAK',90,80]],note:'The transition is the teaching feature; a plain incomer must not inherit this schematic.'},
 chandelle_apex:{path:'M 8 78 Q 50 8 92 78',labels:[['RISING',26,40],['APEX',50,15],['DESCENDING',74,40],['BREAK PHASE',78,51]],note:'Rise, apex and descent are separate phases. Break phase must be chosen before method advice.'},
 rising_teal_under_power:{path:'M 45 90 C 47 66 50 38 58 10',labels:[['UNDER POWER',49,58],['NEAR PEAK',57,17],['BREAK ZONE',52,42]],note:'This lesson is the under-power teal case, not a universal teal picture.'},
 crossing_rabbit:{path:'M 7 78 C 24 75 31 83 47 78 S 71 73 93 78',labels:[['GROUND LINE',30,88],['VARIABLE BOUNCE',50,68],['BREAK ZONE',76,76]],note:'Bounce is shown only as variability; the schematic does not claim to reproduce live ground physics.'},
 driven_incoming:{path:'M 50 8 C 49 34 50 61 53 92',labels:[['INCOMING',50,28],['OVERHEAD TRANSITION',51,58],['BREAK ZONE',52,45]],note:'Conceptual 2D rehearsal only. A wall display cannot reproduce true incoming depth.'},
 pair_planning:{paths:['M 8 34 C 38 32 64 35 92 42','M 8 78 C 34 70 62 55 92 24'],labels:[['BIRD 1',32,33],['BIRD 2',36,68],['TRANSITION',61,48]],note:'Each bird keeps its own geometry; the pair layer teaches order and transition planning.'},
 rising_quartering_outgoing:{path:'M 10 82 C 34 68 58 46 91 18',labels:[['RISING',30,67],['QUARTERING AWAY',55,48],['BREAK ZONE',78,29]],note:'The screen path encodes a rising quartering-away presentation; depth and exact angle are conceptual.'},
 fast_flat_quartering_away:{path:'M 8 68 L 94 34',labels:[['PICKUP',27,61],['FAST / STABLE LINE',51,49],['BREAK ZONE',78,39]],note:'A shallow oblique path represents the fast flat quartering-away geometry. The display does not encode a calibrated live-fire speed or lead.'}
};
function visualHtml(l){const v=visualProfiles[l.id];if(!v)return `<div class="pb-visual-unavailable">No certified schematic is available for this lesson yet.</div>`;const paths=v.paths||[v.path];const pathSvg=paths.map((d,i)=>`<path class="pb-target-path ${i?'secondary':''}" d="${d}" pathLength="100"/>`).join('');const labels=(v.labels||[]).map(([text,x,y])=>`<g class="pb-visual-label"><circle cx="${x}" cy="${y}" r="2.2"/><text x="${x}" y="${Math.max(5,y-5)}" text-anchor="middle">${esc(text)}</text></g>`).join('');return `<figure class="pb-visual" data-visual-id="${esc(l.id)}"><div class="pb-visual-head"><strong>Target geometry</strong><span>SCHEMATIC · NOT TO SCALE</span></div><svg viewBox="0 0 100 100" role="img" aria-label="Schematic target path for ${esc(l.name)}"><defs><marker id="pbArrow-${esc(l.id)}" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0,0 L6,3 L0,6 Z"/></marker></defs><g style="marker-end:url(#pbArrow-${esc(l.id)})">${pathSvg}</g>${labels}</svg><figcaption>${esc(v.note)}</figcaption></figure>`}
function renderLesson(l,focus='learn'){$('#playbookLessonTitle').textContent=l.name;const body=$('#playbookLessonBody');const diag=(l.diagnose||[])[0];const diagBlock=diagnosisHtml(diag);const learn=`<section class="pb-section"><span class="pb-kicker">WHAT YOU'RE SEEING</span><p>${esc(l.understand)}</p>${visualHtml(l)}</section><section class="pb-section"><span class="pb-kicker">COACHING OPTIONS</span>${(l.coaching||[]).map(c=>`<article class="pb-claim"><span class="evidence-pill ${labelClass(c.label)}">${esc(c.label)}</span><p>${esc(c.text)}</p>${c.attribution?`<small>${esc(c.attribution)}</small>`:''}</article>`).join('')}</section>${l.holds?.length?`<section class="pb-section pb-hold"><span class="pb-kicker">DO NOT OVERCLAIM</span>${l.holds.map(h=>`<p>${esc(h)}</p>`).join('')}</section>`:''}`;const rest=`<section class="pb-section"><span class="pb-kicker">VISUAL LESSON SPEC</span><p>${esc(l.visual_spec?.target||'')}</p><ul>${(l.visual_spec?.show||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${l.visual_spec?.warning?`<div class="pb-warning">${esc(l.visual_spec.warning)}</div>`:''}</section><section class="pb-section"><span class="pb-kicker">PRACTICE</span>${(l.drills||[]).map(d=>`<div class="pb-drill"><strong>${esc(d.name)}</strong><span class="evidence-pill ${labelClass(d.label)}">${esc(d.label)}</span></div>`).join('')}</section>`;body.innerHTML=focus==='diagnose'?diagBlock+learn+rest:learn+diagBlock+rest;window.ShotSightPlaybookMotion?.decorate?.()}
function bindSheet(){if($('#playbookSheet')?.dataset.bound)return;$('#playbookSheet')?.setAttribute('data-bound','1');$('#playbookClose')?.addEventListener('click',closeLesson);$('#playbookSheet')?.addEventListener('click',e=>{if(e.target.id==='playbookSheet')closeLesson()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#playbookSheet')?.classList.contains('active'))closeLesson()})}
function init(){bindSheet();setup()}
window.ShotSightPlaybook={init,openLesson};if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();