import { chromium } from 'playwright';
const base=process.env.SHOTSIGHT_BASE_URL||'http://127.0.0.1:8000/';const browser=await chromium.launch({headless:true});let failed=false;
async function choose(page,value){const b=page.locator(`#diagnosisBody [data-answer="${value}"]`);await b.waitFor({state:'visible'});await b.click()}
async function run(label,viewport){const page=await browser.newPage({viewport});const errors=[];page.on('console',m=>{if(m.type()==='error')errors.push(`console: ${m.text()}`)});page.on('pageerror',e=>errors.push(`pageerror: ${e.message}`));try{const response=await page.goto(base,{waitUntil:'networkidle'});if(!response?.ok())throw new Error(`${label}: page HTTP ${response?.status()}`);await page.locator('.tab[data-view="diagnoseView"]').click();await page.locator('[data-diagnose]').click();await page.locator('#diagnosisSheet.active').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelectorAll('#diagnosisBody [data-answer]').length>=12);if(!/PRESENTATION/.test(await page.locator('#diagnosisBody').innerText()))throw new Error(`${label}: presentation-first step missing`);
await choose(page,'flat_long_crosser');await choose(page,'behind');await choose(page,'clear');await choose(page,'supports');const supported=await page.locator('#diagnosisBody').innerText();if(!/SUPPORTED COACHING HYPOTHESIS/.test(supported)||!/Branch supported — not proven/.test(supported)||!/CANDIDATE MECHANISMS/.test(supported)||!/Retest:/.test(supported))throw new Error(`${label}: representative supported branch incomplete`);if(/Strong match|Likely diagnosis/.test(supported))throw new Error(`${label}: legacy overconfidence leaked`);
await page.locator('#diagnosisAgain').click();await choose(page,'flat_long_crosser');await choose(page,'ahead');const uncertain=await page.locator('#diagnosisBody').innerText();if(!/UNCERTAINTY RETAINED/.test(uncertain)||!/will not borrow its fix/i.test(uncertain))throw new Error(`${label}: unmatched symptom uncertainty failed`);
await page.locator('#diagnosisAgain').click();await choose(page,'chandelle_apex');await choose(page,'vertical');await choose(page,'clear');await choose(page,'against');const alternative=await page.locator('#diagnosisBody').innerText();if(!/BRANCH NOT CONFIRMED/.test(alternative)||!/Evidence points away/.test(alternative))throw new Error(`${label}: discriminator confidence reduction failed`);
for(const [id,symptom,term] of [['rising_quartering_outgoing','lose','vertical-intercept'],['fast_flat_quartering_away','behind','quartering approach'],['teal_near_apex','rush','apex method']]){await page.locator('#diagnosisAgain').click();await choose(page,id);await choose(page,symptom);const context=await page.locator('#diagnosisBody').innerText();if(!/ShotSight hypothesis/i.test(context))throw new Error(`${label}: ${id} hypothesis disclosure missing`);await choose(page,'clear');await choose(page,'supports');const expanded=await page.locator('#diagnosisBody').innerText();if(!/SHOTSIGHT_HYPOTHESIS/.test(expanded)||!new RegExp(term,'i').test(expanded))throw new Error(`${label}: ${id} hypothesis-labelled correction missing`)}
if(errors.length)throw new Error(`${label}: browser errors: ${errors.join(' | ')}`);console.log(`PASS ${label}: decision engine plus all three Stage 8 expansion branches verified.`)}finally{await page.close()}}
for(const [label,viewport] of [['diagnosis-mobile-390x844',{width:390,height:844}],['diagnosis-desktop-1280x800',{width:1280,height:800}]]){try{await run(label,viewport)}catch(e){failed=true;console.error(`FAIL ${e.message}`)}}await browser.close();if(failed)process.exit(1);
